### ISSUE TITLE
Fix dataset loading

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco#122]
* Release number or git hash: a30345e481680c94647ae50ae5afd154c8ad77f9

### Steps to reproduce

1. Open https://taco.caleydoapp.org/#ds=Olympic%20Games%20Total%20Medals
2. Wait --> nothing will happen

### Observed behavior

![image](https://user-images.githubusercontent.com/5851088/38804864-2ccdeef4-4174-11e8-8faf-bb0f846714d7.png)

Some datasets are not loading and produce an internal server error. The server log looks like this:

```
10:45:49 ERROR taco_server.api: Exception on /compare/tacoServerOlympicGames1932TotalMedals/tacoServerOlympicGames1936TotalMedals/structure,structure,content,nochange/bar_chart [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/phovea/taco_server/api.py", line 67, in bar_chart
return diff_log(id1, id2, bins_row, bins_col, direction, operations)
File "/phovea/taco_server/api.py", line 45, in diff_log
json_result = diff_cache.get_ratios(id1, id2, direction, operations, br, bc)
File "/phovea/taco_server/src/diff_cache.py", line 140, in get_ratios
diffobj = get_diff_table(id1, id2, direction, ops, False)
File "/phovea/taco_server/src/diff_cache.py", line 97, in get_diff_table
diffobj = calc_diff(id1, id2, direction, all_ops)
File "/phovea/taco_server/src/diff_cache.py", line 215, in calc_diff
d = diff_finder.generate_diff(ops)
File "/phovea/taco_server/src/diff_finder.py", line 775, in generate_diff
has_structure)
File "/phovea/taco_server/src/diff_finder.py", line 831, in _compare_ids
apos = np.where(u_ids == j)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### Expected behavior
* The datasets should load as expected.

**Comment by thinkh** [comment]
Issue moved to [Caleydo/taco_server #15](https://github.com/Caleydo/taco_server/issues/15) via [**ZenHub**](https://www.zenhub.com/)
